//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.03 at 05:16:58 PM CLST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://com/esteban/webservices/personservice", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.esteban.webservices.personservice;
